"""Add personal data fields and views_count to CandidateProfile

Revision ID: 05f65d29ce30
Revises: db77c908c75e
Create Date: 2025-12-06 23:54:47.825044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f65d29ce30'
down_revision = 'db77c908c75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('house_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('views_count')
        batch_op.drop_column('house_number')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
