"""add cep to candidate_profile

Revision ID: 233268a8b6ef
Revises: e7c267d2ab82
Create Date: 2026-02-15 08:50:20.475605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233268a8b6ef'
down_revision = 'e7c267d2ab82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
