"""Add gender to CandidateProfile

Revision ID: 6f8fc67942f4
Revises: 05f65d29ce30
Create Date: 2025-12-07 00:05:04.833522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8fc67942f4'
down_revision = '05f65d29ce30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
