"""Add is_public to CandidateProfile

Revision ID: 8ecdbcfd1266
Revises: c8670489e7a4
Create Date: 2025-12-07 02:29:03.989433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecdbcfd1266'
down_revision = 'c8670489e7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
