"""Add professional fields and experiences to CandidateProfile

Revision ID: c8670489e7a4
Revises: 6f8fc67942f4
Create Date: 2025-12-07 00:53:22.986563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8670489e7a4'
down_revision = '6f8fc67942f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('languages')
        batch_op.drop_column('education_level')

    op.drop_table('candidate_experience')
    # ### end Alembic commands ###
