"""Add employment_type to Job

Revision ID: e7c267d2ab82
Revises: 8ecdbcfd1266
Create Date: 2025-12-07 09:49:40.359454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c267d2ab82'
down_revision = '8ecdbcfd1266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###
